/*
   Agrega los países del catálogo que todavía no existen en dbo.COUNTRIES.
   Se puede ejecutar más de una vez: los nombres ya presentes se omiten.
*/
USE HOTEL_BOOKINGS;
GO

INSERT INTO dbo.COUNTRIES (country_name)
SELECT source.country_name
FROM (VALUES
    (N'Afghanistan'),
    (N'Albania'),
    (N'Algeria'),
    (N'Andorra'),
    (N'Angola'),
    (N'Antigua and Barbuda'),
    (N'Argentina'),
    (N'Armenia'),
    (N'Australia'),
    (N'Austria'),
    (N'Azerbaijan'),
    (N'Bahamas'),
    (N'Bahrain'),
    (N'Bangladesh'),
    (N'Barbados'),
    (N'Belarus'),
    (N'Belgium'),
    (N'Belize'),
    (N'Benin'),
    (N'Bhutan'),
    (N'Bolivia'),
    (N'Bosnia and Herzegovina'),
    (N'Botswana'),
    (N'Brazil'),
    (N'Brunei'),
    (N'Bulgaria'),
    (N'Burkina Faso'),
    (N'Burundi'),
    (N'Cabo Verde'),
    (N'Cambodia'),
    (N'Cameroon'),
    (N'Canada'),
    (N'Central African Republic'),
    (N'Chad'),
    (N'Chile'),
    (N'China'),
    (N'Colombia'),
    (N'Comoros'),
    (N'Congo'),
    (N'Costa Rica'),
    (N'Cote d''Ivoire'),
    (N'Croatia'),
    (N'Cuba'),
    (N'Cyprus'),
    (N'Czechia'),
    (N'Democratic Republic of the Congo'),
    (N'Denmark'),
    (N'Djibouti'),
    (N'Dominica'),
    (N'Dominican Republic'),
    (N'Ecuador'),
    (N'Egypt'),
    (N'El Salvador'),
    (N'Equatorial Guinea'),
    (N'Eritrea'),
    (N'Estonia'),
    (N'Eswatini'),
    (N'Ethiopia'),
    (N'Fiji'),
    (N'Finland'),
    (N'France'),
    (N'Gabon'),
    (N'Gambia'),
    (N'Georgia'),
    (N'Germany'),
    (N'Ghana'),
    (N'Greece'),
    (N'Grenada'),
    (N'Guatemala'),
    (N'Guinea'),
    (N'Guinea-Bissau'),
    (N'Guyana'),
    (N'Haiti'),
    (N'Honduras'),
    (N'Hungary'),
    (N'Iceland'),
    (N'India'),
    (N'Indonesia'),
    (N'Iran'),
    (N'Iraq'),
    (N'Ireland'),
    (N'Israel'),
    (N'Italy'),
    (N'Jamaica'),
    (N'Japan'),
    (N'Jordan'),
    (N'Kazakhstan'),
    (N'Kenya'),
    (N'Kiribati'),
    (N'Kuwait'),
    (N'Kyrgyzstan'),
    (N'Laos'),
    (N'Latvia'),
    (N'Lebanon'),
    (N'Lesotho'),
    (N'Liberia'),
    (N'Libya'),
    (N'Liechtenstein'),
    (N'Lithuania'),
    (N'Luxembourg'),
    (N'Madagascar'),
    (N'Malawi'),
    (N'Malaysia'),
    (N'Maldives'),
    (N'Mali'),
    (N'Malta'),
    (N'Marshall Islands'),
    (N'Mauritania'),
    (N'Mauritius'),
    (N'Mexico'),
    (N'Micronesia'),
    (N'Moldova'),
    (N'Monaco'),
    (N'Mongolia'),
    (N'Montenegro'),
    (N'Morocco'),
    (N'Mozambique'),
    (N'Myanmar'),
    (N'Namibia'),
    (N'Nauru'),
    (N'Nepal'),
    (N'Netherlands'),
    (N'New Zealand'),
    (N'Nicaragua'),
    (N'Niger'),
    (N'Nigeria'),
    (N'North Korea'),
    (N'North Macedonia'),
    (N'Norway'),
    (N'Oman'),
    (N'Pakistan'),
    (N'Palau'),
    (N'Palestine'),
    (N'Panama'),
    (N'Papua New Guinea'),
    (N'Paraguay'),
    (N'Peru'),
    (N'Philippines'),
    (N'Poland'),
    (N'Portugal'),
    (N'Qatar'),
    (N'Romania'),
    (N'Russia'),
    (N'Rwanda'),
    (N'Saint Kitts and Nevis'),
    (N'Saint Lucia'),
    (N'Saint Vincent and the Grenadines'),
    (N'Samoa'),
    (N'San Marino'),
    (N'Sao Tome and Principe'),
    (N'Saudi Arabia'),
    (N'Senegal'),
    (N'Serbia'),
    (N'Seychelles'),
    (N'Sierra Leone'),
    (N'Singapore'),
    (N'Slovakia'),
    (N'Slovenia'),
    (N'Solomon Islands'),
    (N'Somalia'),
    (N'South Africa'),
    (N'South Korea'),
    (N'South Sudan'),
    (N'Spain'),
    (N'Sri Lanka'),
    (N'Sudan'),
    (N'Suriname'),
    (N'Sweden'),
    (N'Switzerland'),
    (N'Syria'),
    (N'Tajikistan'),
    (N'Tanzania'),
    (N'Thailand'),
    (N'Timor-Leste'),
    (N'Togo'),
    (N'Tonga'),
    (N'Trinidad and Tobago'),
    (N'Tunisia'),
    (N'Turkiye'),
    (N'Turkmenistan'),
    (N'Tuvalu'),
    (N'Uganda'),
    (N'Ukraine'),
    (N'United Arab Emirates'),
    (N'United Kingdom'),
    (N'United States'),
    (N'Uruguay'),
    (N'Uzbekistan'),
    (N'Vanuatu'),
    (N'Vatican City'),
    (N'Venezuela'),
    (N'Vietnam'),
    (N'Yemen'),
    (N'Zambia'),
    (N'Zimbabwe')
) AS source(country_name)
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.COUNTRIES AS existing
    WHERE existing.country_name = source.country_name
);
GO
